language: groovy
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
deploy:
  provider: heroku
  api_key: "iYqu73tUE6txuHSsHtH2"
  on:
      all_branches: true
script: "./grailsw refresh-dependencies && ./grailsw test-app unit:"
